# Generated by Django 5.0.1 on 2024-01-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trajetoria_pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='trajetoria pessoal')),
                ('description', models.TextField(verbose_name='trajetoria pessoal')),
            ],
            options={
                'verbose_name': 'trajetoria pessoal',
                'verbose_name_plural': 'trajetoria pessoal ',
            },
        ),
        migrations.CreateModel(
            name='trajetoria_profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='trajetoria profissional')),
                ('image', models.ImageField(upload_to='works')),
            ],
            options={
                'verbose_name': 'trajetoria profissional',
                'verbose_name_plural': 'trajetoria profissional',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='RecentWork',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
