# Generated by Django 5.0.1 on 2024-01-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trajetoria_pessoal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Sobre mim', 'verbose_name_plural': 'Sobre mim'},
        ),
        migrations.AlterModelOptions(
            name='trajetoria_pessoal',
            options={'verbose_name': 'Trajetória Pessoal', 'verbose_name_plural': 'Trajetória Pessoal'},
        ),
        migrations.AlterModelOptions(
            name='trajetoria_profissional',
            options={'verbose_name': 'Trajetória Profissional', 'verbose_name_plural': 'Trajetória Profissional'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='About'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='about',
            name='short_description',
            field=models.TextField(verbose_name='Descrição Breve'),
        ),
        migrations.AlterField(
            model_name='trajetoria_pessoal',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='trajetoria_pessoal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trajetoria_pessoal'),
        ),
        migrations.AlterField(
            model_name='trajetoria_pessoal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='trajetoria_profissional',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='trajetoria_profissional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='works'),
        ),
        migrations.AlterField(
            model_name='trajetoria_profissional',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
