# Generated by Django 5.0.1 on 2024-01-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_options_alter_trajetoria_pessoal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='imagem',
            new_name='image',
        ),
    ]
