# Generated by Django 5.0.1 on 2024-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_imagem_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='certificates/')),
            ],
            options={
                'verbose_name': 'Certificados',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
